### ISSUE TITLE
Add Support for Commands API


### ISSUE THREAD

**Issue by kristinpeterson** [attm2x/m2x-erlang#2]
Add support for the [Commands API](https://m2x.att.com/developer/documentation/v2/commands).

**Comment by jemc** [comment]
Added in [v1.2.0](https://github.com/attm2x/m2x-erlang/releases/tag/v1.2.0).

**Comment by kristinpeterson** [comment]
@jemc thank you Joe!  Closing this issue.

**Comment by jemc** [comment]
Sorry, I meant to close it! :wink:

**Comment by kristinpeterson** [comment]
@jemc no worries!
