### ISSUE TITLE
Add Support for Device/Distribution/Collection Metadata Endpoints

### ISSUE THREAD

**Issue by kristinpeterson** [attm2x/m2x-erlang#3]
See [Ruby library implementation](https://github.com/attm2x/m2x-ruby/commit/044b282afd614e87e68b7516353d65cbe3c79ab0) for reference.

Add support for the following endpoints:

Device Metadata:
* https://m2x.att.com/developer/documentation/v2/device#Read-Device-Metadata
* https://m2x.att.com/developer/documentation/v2/device#Update-Device-Metadata
* https://m2x.att.com/developer/documentation/v2/device#Read-Device-Metadata-Field
* https://m2x.att.com/developer/documentation/v2/device#Update-Device-Metadata-Field

Distribution Metadata:
* https://m2x.att.com/developer/documentation/v2/distribution#Read-Distribution-Metadata
* https://m2x.att.com/developer/documentation/v2/distribution#Update-Distribution-Metadata
* https://m2x.att.com/developer/documentation/v2/distribution#Read-Distribution-Metadata-Field
* https://m2x.att.com/developer/documentation/v2/distribution#Update-Distribution-Metadata-Field

Collection Metadata:
* https://m2x.att.com/developer/documentation/v2/collections#Read-Collection-Metadata
* https://m2x.att.com/developer/documentation/v2/collections#Update-Collection-Metadata
* https://m2x.att.com/developer/documentation/v2/collections#Read-Collection-Metadata-Field
* https://m2x.att.com/developer/documentation/v2/collections#Update-Collection-Metadata-Field

**Comment by jemc** [comment]
Done in f5a06f085138fb023b332674e648fba0e499de10, 221b8fb559c0a8ea4d318edb6a9c5162df636d0b, and 1547919e632a07e2acb622e4acf636506fa19e7b.
